version: 2

sources:
  - name: staging
    database: datatalent-simplon
    schema: staging
    tables:
      - name: offres_enriched_clean
      - name: offres_staging
      - name: adzuna_jobs_clean
